### ISSUE TITLE
symfony comparision

### ISSUE THREAD

**Issue by ahundiak** [capsulephp/comparison#1]
You mentioned on Reddit that you had some trouble with the Symfony container.  Not surprising.  99% of the documentation focuses on using configuring the container within the framework.  What little standalone documentation there is can be misleading and incomplete.

In any event, here is a working Symfony comparison:
```
require __DIR__ . '/psr-11-v1/vendor/autoload.php';
require __DIR__ . '/setup.php';

use Symfony\Component\DependencyInjection\ContainerBuilder;

$container = new ContainerBuilder();

$container->register(PDO::class,PDO::class)
    ->setArguments([
      '%env(DB_DSN)%',
      '%env(DB_USERNAME)%',
      '%env(DB_PASSWORD)%',
    ]);

$container->autowire(Foo::class,Foo::class)->setPublic(true)
    ->setArgument('$bar','bar-wrong')
    ->setArgument('$baz','baz-right');

$container->getDefinition(Foo::class)->setArgument('$bar','bar-right');

putenv('DB_DSN=sqlite::memory:');
putenv('DB_USERNAME=db_user');
putenv('DB_PASSWORD=db_password');

$container->compile(true);

echo "Symfony" . PHP_EOL;
output($container, 'get');
```
As expected, registering a service and then changing an argument is trivial.

You will notice that I had to execute the putenv functions before compiling.  The compiles(true) process basically inlines the values of the env variables.  Which is fine.  As a rule I don't think you want env values changing as an application runs.  However it might qualify as one of your 'completes but' notes?

It should be pointed out that within the framework, the container is written out as a cached php file and then read back in.  In this scenario, the env values are not actually read until a service is requested.  I could have done that here but I'm pretty sure that would qualify as 'extra effort'.  It only takes a couple of lines but does require an extra dependency.  But doing so would have eliminated the need for executing putenv first.

**Comment by pmjones** [comment]
@ahundiak Dude this is beautiful. Let me get back to you on incorporating it. Thanks a ton!

**Comment by pmjones** [comment]
@ahundiak I have added the symfony code as you wrote it, but had to say on consideration that changing the conditions fo the test to define the environment first counts as a "does not complete the scenario." However, you said:

> It should be pointed out that within the framework, the container is written out as a cached php file and then read back in. In this scenario, the env values are not actually read until a service is requested. I could have done that here but I'm pretty sure that would qualify as 'extra effort'. It only takes a couple of lines but does require an extra dependency. But doing so would have eliminated the need for executing putenv first.

If you can point out how to pull that off, I'm fine with showing what's needed to pass the scenario-as-written, so that the conditions remain the same for all the containers under consideration. Extra-effort/extra-dependency is not a deal-breaking on that point.

Thanks again for your time and attention here!
